// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (CategoryGroup, error)
	CreatePayee(ctx context.Context, arg CreatePayeeParams) (Payee, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmails(ctx context.Context, arg CreateVerifyEmailsParams) (VerifyEmail, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DeleteAccounts(ctx context.Context, budgetID uuid.UUID) error
	DeleteBudget(ctx context.Context, id uuid.UUID) error
	DeleteBudgets(ctx context.Context, ownerUsername string) error
	DeleteCategories(ctx context.Context, categoryGroupID uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteCategoryGroup(ctx context.Context, id uuid.UUID) error
	DeleteCategoryGroups(ctx context.Context, budgetID uuid.UUID) error
	DeletePayee(ctx context.Context, arg DeletePayeeParams) error
	DeleteTransaction(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, username string) error
	DeleteUserSessions(ctx context.Context, username string) error
	DeleteVerifyEmails(ctx context.Context, username string) error
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetAccounts(ctx context.Context, budgetID uuid.UUID) ([]Account, error)
	GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error)
	GetBudgetAccount(ctx context.Context, arg GetBudgetAccountParams) (GetBudgetAccountRow, error)
	GetBudgetDetails(ctx context.Context, arg GetBudgetDetailsParams) (Budget, error)
	GetBudgets(ctx context.Context, ownerUsername string) ([]Budget, error)
	GetCategories(ctx context.Context, categoryGroupID uuid.UUID) ([]Category, error)
	GetCategory(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryGroup(ctx context.Context, id uuid.UUID) (CategoryGroup, error)
	GetCategoryGroupsByBudgetId(ctx context.Context, budgetID uuid.UUID) ([]CategoryGroup, error)
	GetPayeeById(ctx context.Context, id uuid.UUID) (Payee, error)
	GetPayees(ctx context.Context, budgetID uuid.UUID) ([]Payee, error)
	GetPendingVerifyEmails(ctx context.Context, arg GetPendingVerifyEmailsParams) ([]VerifyEmail, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTransactions(ctx context.Context, budgetID uuid.UUID) ([]Transaction, error)
	GetTransactionsById(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionsView(ctx context.Context, budgetID uuid.UUID) ([]TransactionsView, error)
	GetTransactionsViewById(ctx context.Context, id uuid.UUID) (TransactionsView, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	GetVerifyEmails(ctx context.Context, arg GetVerifyEmailsParams) (VerifyEmail, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryGroup(ctx context.Context, arg UpdateCategoryGroupParams) (CategoryGroup, error)
	UpdateCodeUsed(ctx context.Context, code string) (VerifyEmail, error)
	UpdatePayee(ctx context.Context, arg UpdatePayeeParams) (Payee, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
