// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/guerzon/gobudget-api/pkg/worker (interfaces: TaskDistributor)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination pkg/mock/worker.go github.com/guerzon/gobudget-api/pkg/worker TaskDistributor
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	worker "github.com/guerzon/gobudget-api/pkg/worker"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeSendEmail mocks base method.
func (m *MockTaskDistributor) DistributeSendEmail(arg0 context.Context, arg1 *worker.SendEmailPayload, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeSendEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeSendEmail indicates an expected call of DistributeSendEmail.
func (mr *MockTaskDistributorMockRecorder) DistributeSendEmail(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeSendEmail", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeSendEmail), arg0, arg1, arg2)
}
